version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - "9200"
      - "9300"
    networks:
      - TraceLog
    environment: 
      ES_JAVA_OPTS: -Xms256m -Xmx512m
      discovery.type: single-node

  kibana:
    image: kibana:7.8.1
    ports:
      - "5601:5601"
    networks:
      - TraceLog
    environment:
      - I18N_LOCALE=zh-CN

networks:
  TraceLog: