version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - "2181"
    networks:
      - TraceLog

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    networks:
      - TraceLog
    environment: 
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: -Xms128m -Xmx256m

networks:
  TraceLog: